package com.example.examplemod.hive.pop;

import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.geom.ModelLayers;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.client.renderer.entity.MobRenderer;
import net.minecraft.client.renderer.entity.layers.HumanoidArmorLayer;
import net.minecraft.resources.ResourceLocation;

/**
 * One renderer for all five dwellers.
 *
 * <h2>Why the humanoid layout and not the villager one</h2>
 *
 * The citizen uses {@code VillagerModel} with the vanilla villager texture, and the obvious move was
 * to do the same here with the villager profession textures — mason for the worker, cleric for the
 * priest. It does not work: those files are <b>overlays</b>, drawn on top of the villager base by
 * the vanilla renderer's layers, and used alone they render a mostly-transparent person.
 *
 * <p>So these use {@link ModelLayers#ZOMBIE} — the standard 64×64 humanoid layout that all eleven
 * Imperial troops already use, and the one {@code tools/generate_troop_textures.py} knows how to
 * paint. That let the dweller textures be generated by importing the existing painter rather than
 * writing a second one for a second layout.
 *
 * <p>The texture comes off {@link HiveRole}, which is a field on the entity rather than a lookup, so
 * a render call is a field read and nothing else — the same rule
 * {@code ImperialTroopAppearance} follows for the troops.
 */
public class HiveDwellerRenderer extends MobRenderer<HiveDwellerEntity, HumanoidModel<HiveDwellerEntity>> {

    public HiveDwellerRenderer(EntityRendererProvider.Context context) {
        super(context, new HumanoidModel<>(context.bakeLayer(ModelLayers.ZOMBIE)), 0.5F);

        // Armour layer so a dweller given a helmet by a command or a future mechanic actually shows
        // it. Costs nothing when the slots are empty, which is the normal case.
        addLayer(new HumanoidArmorLayer<>(this,
                new HumanoidModel<>(context.bakeLayer(ModelLayers.ZOMBIE_INNER_ARMOR)),
                new HumanoidModel<>(context.bakeLayer(ModelLayers.ZOMBIE_OUTER_ARMOR)),
                context.getModelManager()));
    }

    @Override
    public ResourceLocation getTextureLocation(HiveDwellerEntity entity) {
        return entity.role().texture();
    }
}
