package com.example.examplemod.campaign;

/**
 * What kind of theatre a {@link CampaignFront} is, which decides how the campaign treats it.
 *
 * <p>Deliberately small. Each value must earn itself by changing behaviour somewhere — a type that
 * only changes a label belongs in a translation key, not here.
 */
public enum CampaignFrontType {
    /**
     * A world with a surface: settlements are seeded on it, sectors are laid out around its spawn,
     * and both sides expand across it. The nine worlds of {@code FCPlanets}.
     */
    PLANET("planet"),

    /**
     * A built interior — the Hive World. Flat, generated by the Hive tooling rather than by terrain
     * noise, so nothing scatters settlements across it and its sectors are the Hive's own levels.
     * It still has an owner, sectors and objectives, which is why it is a front at all.
     */
    HIVE("hive"),

    /**
     * A place that is not fixed to a world: the Space Hulk the roadmap ends with. It has sectors and
     * an owner like anything else, but it has no spawn to seed around and it can vanish. Nothing
     * generates one yet — the value exists so the campaign's storage and commands already handle a
     * front that is not a planet, rather than being retrofitted for it later.
     */
    VOID("void");

    private final String key;

    CampaignFrontType(String key) {
        this.key = key;
    }

    public String key() {
        return this.key;
    }

    public static CampaignFrontType fromName(String name) {
        if (name != null) {
            for (CampaignFrontType type : values()) {
                if (type.name().equalsIgnoreCase(name)) {
                    return type;
                }
            }
        }

        return PLANET;
    }
}
