package com.example.examplemod;

public enum ImperialCommandCoreAction {
    DEPOSIT_RESOURCES,
    BUILD_IMPERIAL_MINE,
    BUILD_GOLD_MINE,
    BUILD_SCRAP_YARD,
    BUILD_IMPERIAL_FORGE,
    BUILD_PROMETHIUM_REFINERY,
    BUILD_FARM,
    BUILD_EMERALD_TRADE_DEPOT,
    BUILD_BARRACKS,
    WITHDRAW_IRON,
    WITHDRAW_COAL,
    WITHDRAW_SCRAP,
    WITHDRAW_GOLD,
    WITHDRAW_EMERALD,
    WITHDRAW_CRUSADIUM,
    RECRUIT_GUARDSMAN,
    CYCLE_SPECIALIST,
    PROMOTE_SPECIALIST,
    UPGRADE_CITY,
    REPAIR_CORE,
    CALL_REINFORCEMENTS,
    RALLY_DEFENDERS,
    FORTIFY_DEFENDERS,
    FORCE_RAID_TEST
}