package com.example.examplemod;

public enum ImperialCommandCoreAction {
    DEPOSIT_RESOURCES,
    BUILD_IMPERIAL_MINE,
    BUILD_GOLD_MINE,
    BUILD_SCRAP_YARD,
    BUILD_IMPERIAL_FORGE,
    BUILD_PROMETHIUM_REFINERY,
    BUILD_FARM,
    BUILD_EMERALD_TRADE_DEPOT,
    BUILD_BARRACKS,
    GIVE_BUILDER_TOOL,
    WITHDRAW_IRON,
    WITHDRAW_COAL,
    WITHDRAW_SCRAP,
    WITHDRAW_GOLD,
    WITHDRAW_EMERALD,
    WITHDRAW_CRUSADIUM,
    WITHDRAW_FOOD,
    RECRUIT_GUARDSMAN,
    CYCLE_SPECIALIST,
    PROMOTE_SPECIALIST,

    /** Commission a Battle Tank from the Crusade's vehicle industry (see ArmourRequisition). */
    REQUISITION_ARMOUR,
    UPGRADE_CITY,
    REPAIR_CORE,
    CALL_REINFORCEMENTS,
    RALLY_DEFENDERS,
    FORTIFY_DEFENDERS,
    FORCE_RAID_TEST,
    TOGGLE_GOVERNANCE,
    SURVEY_BORDER
}